version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.test
    environment:
      CONDUIT_API_BASE_URL: http://test.conduit.com
      CONDUIT_API_VERSION: v1
