matrix:
  include:
    - language: node_js
      node_js:
        - 11.4.0
      before_install:
        - cd ./client/react
      cache:
        directories:
          - node_modules
      branches:
        only:
          - /^client\/react(?:-.*)?/
      script:
          - npm test
      before_deploy:
        - cd ./client/react
      deploy:
        app: santiaro90-conduit-react
        provider: heroku
        api_key:
          secure: OSYKw32iT/V4U4OZUDM8kwS6crM9Hyb1MgFnRpTUdRS5znt3oi3WCCmKthLDqz9d7SKQ9BIL3K0lGTDtAOvWlMGKEX6pJe4fkJnvZNCwCGi4CUYQoVCOgQWVass/3Ru5jw/SVRuAg8c8PE6kXOAghhiOtqf1FAD1wyJMExcSytR0xmnTx2lx5UDwhh+ykCzwL5DWvkD92GnaSNTn1zTj/WFIjcdjUnIg2Jksau1WGdDj12xd3JumDU6BkrBX1ADX+joFGXEkG6tLSLoy8gILcjwGHeGix+KxNFgqE1t66qO2WIBmzx0rP18GFDbj10IqwrPxrk9PLqHAkfULVo/tibYp0FGlUIxuaA+8D9sfmHdjQ2DKg97m+8SEWHfTJTavZM+tsSAaZZ9RlLYPrnUgEt55mAgAiJ6j5upU4rFSKQGDVmJugoBAaxs4kCjz8wosBhnYZfqBfMVyFe/65QRmWhhOF+8EnaXpwwii1Qil7mj1BuYrntsOeSLFXSELJ3kQq5KvlDfvFKjLsSiPvsd8awJ+VctA+fPLAYqdau74icdTE9uZ5yvFCb5bC4KWfL81vvBoc1RdD4GAfGFJFanRsvyn5VgISXzQsda/+AL5S39pECBSPYMVYrZFoS0y1LK4i8X6mF1K2QghZlubWmx/NDWxHLZbauqRrGubNTyTeNQ=
        on: master
