install: true
services:
  - docker

heroku: &heroku
  provider: heroku
  api_key:
    secure: rqjorQA2byNhDchCCRmJZZKmaMtZoPsBPSjZMCX1K8XlxFl9qu/8YLD5AqEtySqPKaeQqyJh8MlgSgNQGxZ4YZJPJD+h6HW4sgHETCTayHGmHpSQeHzzASPsV4pUiVUVx79cqHWxwhEj7yWrA4LlJYQ9I6P2xIyZM6NB9n1iT6DsF1UdockeK19em4iYTV1V4mAU3T6VMqrnrE4BdRMWilFhbQ+GLFK+jbGfK/12KLpGjYjKL8n3rPbloT0GEpvE1PcFEhZrcnJAv1VYEhPfK0ZtrOnz7aiG6sLCQbz6ygpnlBfgthRZ2EqID1lVr0VNQELSdhy+//sPiXzKO/NbXfPytykG0Fqii++AgFUTkCkhUrI9hgtjl7nB+2YEbJXSBcEJb6qBLujdttk7GG0vwAPU9s05LWlUUNdhbaBfRF1EwNctKWTZQ71UqxFlNtQBjwagbUp/HLNeF0ezpXMZsslS/L3rC8Up64lpTEuUqQopeWQEMgE2CQddqVH0Bv+NeIzv+r31RLnUihYH4ZHPwvHBD5kuKKS03PymWtC98sNM5gxLQ5PoXd8/Tcz4oFc6CkERd6GOfVAvwegRP5QhRfhzAjJLf7jMuKtUqcYAI4YmgOQpQ5gr9dlIK20ri0jmNRfh0mS89NBNZ7tNq2VLzSqSn0eJYgbHg7G0oih2bTw=
  on: master

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      language: ruby
      branches:
        only:
          - master
          - "/^api\\/rails(?:-.*)?/"
      env:
        - secure: M2h/GWP8u4H2dslkya4QS3imStb31XHtQ35OHL23rI0FiygBp0Ir9Fw1DEFI1ymLOrtj3Cf42Bbtwnt8L0Rfr+qJYp6/j18HyODr8FkoO4/N/RLLHw+zzfws8/oPoxHDkSH78UErTcxv+11c4DRDp1gR/6tae1CAaJQZp2SUCPN+XXKiPkxZxraYUQwtxfA+vgoenioaAYocKyrnKw4VtNbLTos+Jo12FbijbV8d+eLg/4P9B0xR09NPc8uNSTAdkPZzRSR20JiYTNveJu4XY9Wx9CTYA2bIilDaI5ToHBmYspoknHu8v7BzrqX4NSG4Lp6C6dNUL1rKqUm6RtJPLp0ycgBbrzq9UI+eco3Hn2BDitOcYHlwNzgSZVZTT5fpC3CkUJ3VayuUsgatbABDHJzTj6n7ijm4b64nK2wajfCFFSvAdECPs+xUOsTBF8Yqwi+eFX9UbKYUk2daHKT/lpdDFSGy+jaEBBBfrrqhYW0hVfpASQplwo1pBlXJR8/3J7Y7NEI3yWNty0WpCiU5+FBijXy1LbsusNpmF8Lgc5/HPsiIy4o5eqM7dpqXa9YR/5kP54MpXR38q9M6+Dt0nY1XuhEOBzPLcbXNOw7v7XQS4knX9CCIfXn3XRRJb9jWKA4Cvh0CulHyBVnFcetsn0VkJDv/qxWa/8IesUac+Ak=
      script:
        - ./scripts/run-tests-api rails api

    - stage: test
      language: node_js
      branches:
        only:
          - master
          - "/^client\\/react(?:-.*)?/"
      script:
        - ./scripts/run-tests-web react web

    # Deploy React
    - stage: deploy
      language: node_js
      script: skip
      before_deploy:
        - cd ./client/react
      deploy:
        <<: *heroku
        app: santiaro90-conduit-react

    # Deploy Rails
    - stage: deploy
      language: ruby
      script: skip
      before_deploy:
        - cp ./scripts/rds-ca-cert.pem ./api/rails/config
        - cd ./api/rails
      deploy:
        <<: *heroku
        app: santiaro90-conduit-rails
        run: bin/rails db:migrate
        skip_cleanup: true
