version: '3'
services:
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    environment:
      CONDUIT_DATABASE: conduit_dev
      CONDUIT_DATABASE_HOST: db
      CONDUIT_DATABASE_USERNAME: conduit
      CONDUIT_DATABASE_PASSWORD: conduit
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    ports:
      - 3000:80
    volumes:
      - ../:/opt/conduit
    networks:
      - conduit-dev
    depends_on:
      - db

  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: conduit_dev
      MYSQL_USER: conduit
      MYSQL_PASSWORD: conduit
    volumes:
      - conduit-dev-db:/var/lib/mysql
    networks:
      - conduit-dev
volumes:
  conduit-dev-db:
networks:
  conduit-dev:
    external: true
