# vim: set ft=dockerfile :
FROM conduit-rails

WORKDIR /opt/conduit

ENV RAILS_ENV=test

COPY config/database.ci.yml ./config/database.yml

CMD ["sh", "-c", \
     "echo 'Waiting for MySQL to be ready...'; \
     wait-for db:3306 -t 20 -- bin/rails spec"]
