# vim: set ft=dockerfile :
FROM conduit-rails

WORKDIR /var/www/conduit

ENV RAILS_ENV=test

CMD ["sh", "-c", \
     "echo 'Waiting for MySQL to be ready...'; \
     wait-for db:3306 -t 20 -- bin/rails spec"]
