#!/bin/bash
set -e -x

# Set docker-compose containers' prefix
export COMPOSE_PROJECT_NAME=conduit-test

docker_compose_base=./docker-compose.yml
docker_compose_file=./docker-compose.test.yml

# Run tests and clean up containers
docker-compose -f $docker_compose_base -f $docker_compose_file run --rm api
docker-compose -f $docker_compose_base -f $docker_compose_file down --rmi local --remove-orphans
