#!/bin/bash
set -e -x

# project == api | client
# stack == a subdirectory of api or client, e.g react
project="${1:-api}"
stack="${2:-rails}"

shift 2

# Service defined in ./docker/$stack/docker-compose.test.yml that runs the
# tests
service="$1"

if [[ -z $service ]]; then
  echo 'run-tests: you must provide a service to run the tests'
  exit 1
fi

# Set docker-compose containers' prefix
export COMPOSE_PROJECT_NAME=conduit-test-$stack

base_compose_file=./$project/$stack/docker/docker-compose.yml
test_compose_file=./$project/$stack/docker/docker-compose.test.yml

if [[ -f $test_compose_file ]]; then
  docker-compose -f $base_compose_file -f $test_compose_file run --rm $*
  docker-compose -f $base_compose_file -f $test_compose_file down --rmi local
else
  docker-compose -f $base_compose_file run --rm $*
  docker-compose -f $base_compose_file down --rmi local
fi
