# vim: set ft=dockerfile :
FROM conduit-base

WORKDIR /var/www/conduit

ENV RAILS_ENV=test

RUN rm config/database.yml && mv config/database.ci.yml config/database.yml

CMD ["sh", "-c", \
     "echo 'Waiting for MySQL to be ready...'; \
     wait-for db:3306 -t 20 -- bin/rails spec"]
