extends:
  - react-app
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'
  - prettier

rules:
  '@typescript-eslint/no-unused-vars': 2
  '@typescript-eslint/prefer-interface': 0
  '@typescript-eslint/explicit-function-return-type':
    - 2
    - allowTypedFunctionExpressions: true
  prettier/prettier: 0
  react/jsx-sort-props:
    - 2
    - shorthandLast: true
    - ignoreCase: false
