#!/bin/bash
set -e -x

if [[ $# -lt 2 ]]; then
  echo 'run-tests-api: you must provide the stack and service to test'
  echo
  echo 'Usage: run-tests-api <api> <service>'
  echo '  api       a subfolder of ./api'
  echo '  service   the service defined in ./api/$api/docker/docker-compose.test.yml'
  echo '            that will run your tests'
  echo
  echo '  Example: run-tests-api rails api'

  exit 1
fi

api="$1"
service="$2"

./scripts/build-base-image api $api

shift 2

cov_volume="-v $PWD/coverage:/opt/conduit/coverage"

./scripts/coverage-env

# Set docker-compose options
export COMPOSE_PROJECT_NAME=conduit-test
export COMPOSE_FILE=$PWD/api/$api/docker/docker-compose.test.yml

docker-compose build $service
docker-compose run $cov_volume --rm $service $*

./scripts/collect-coverage $api

docker-compose down --rmi local
