#!/bin/bash
set -e -x

if [[ $# -lt 2 ]]; then
  echo 'run-tests-web: you must provide the stack and service to test'
  echo
  echo 'Usage: run-tests-web <client> <service>'
  echo '  client     a subfolder of ./client'
  echo '  service    the service defined in ./client/$client/docker/docker-compose.test.yml'
  echo '             that will run your tests'
  echo
  echo '  Example: run-tests-web react web'

  exit 1
fi

client="$1"
service="$2"

./scripts/build-base-image client $client

shift 2

cov_volume="-v $PWD/coverage:/opt/conduit/coverage"

# Set docker-compose containers' prefix
export COMPOSE_PROJECT_NAME=conduit-test
export COMPOSE_FILE=$PWD/client/$client/docker/docker-compose.test.yml

./scripts/coverage-env

docker-compose build $service $*
docker-compose run $cov_volume --rm $service $*

./scripts/collect-coverage $client

docker-compose down --rmi local
